### PR TITLE
Change license to AGPLv3

### PR DESCRIPTION
**Pull request by mirkobrombin**
I'm proposing to switch from the [MIT](https://choosealicense.com/licenses/mit/) to the [AGPLv3](https://choosealicense.com/licenses/agpl-3.0/) License for this repository.

### Short
Permissions of this strongest copyleft license are conditioned on making available complete source code of licensed works and modifications, which include larger works using a licensed work, under the same license. Copyright and license notices must be preserved. Contributors provide an express grant of patent rights. When a modified version is used to provide a service over a network, the complete source code of the modified version must be made available.

### Important benefits

...

  A secondary benefit of defending all users' freedom is that
improvements made in alternate versions of the program, if they
receive widespread use, become available for other developers to
incorporate.  Many developers of free software are heartened and
encouraged by the resulting cooperation.  However, in the case of
software used on network servers, this result may fail to come about.
The GNU General Public License permits making a modified version and
letting the public access it on a server without ever releasing its
source code to the public.

...

  The GNU Affero General Public License is designed specifically to
ensure that, in such cases, the modified source code becomes available
to the community.  It requires the operator of a network server to
provide the source code of the modified version running there to the
users of that server.  Therefore, public use of a modified version, on
a publicly accessible server, gives the public access to the source
code of the modified version.

### Sign the License change
This repository has received changes from several contributors and I therefore ask for your permission to make this change (or not in case you are against). "Sign" this PR with a simple message.

- [x] @mirkobrombin
- [x] @francescomasala 
- [x] @AlexzanDev 
- [x] @Martinligabue
- [x] @henrybarreto
- [x] @ldsands
- [x] @HammyHavoc

### CODE REVIEW

**Comment by francescomasala** [comment]
I'm fine with this license change

**Comment by AlexzanDev** [comment]
Signed!

**Comment by HammyHavoc** [comment]
Signed!

**Comment by Martinligabue** [comment]
Seems a nice change

**Comment by TheEvilSkeleton** [comment]
Pinging once more...
- @henrybarreto
- @ldsands

**Comment by henrybarreto** [comment]
Signed!

**Comment by mirkobrombin** [comment]
Thanks everyone for approving.

**Comment by TheEvilSkeleton** [comment]
I contributed to the website just today. I sign.

**Pull request merged**
